# CD workflow to deploy Android app to staging and production.
# Defines deploy-to-staging and deploy-to-production jobs.
# Each job downloads build artifact and runs deployment scripts.
# Workflow is reusable and triggered via workflow_call.
# Inputs and secrets can be passed in.

run-name: Gradle CD (staging)
on:
  workflow_call: # required when creating a reusable workflow
#    inputs:
#      config-path:
#        required: false
#        type: string
#    secrets:
#      token:
#        required: false
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      #      - name: Download build
      #          uses: actions/download-artifact@v3
      #          with:
      #            name: Package

      - name: Run CD for Staging
        run: |
          echo Perform deployment steps for the staging environment

  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      #      - name: Download build
      #        uses: actions/download-artifact@v3
      #        with:
      #          name: Package (will grab apk files for build in cloud environment)

      - name: Run CD for Production
        run: |
          echo Perform deployment steps for the production environment