name: CI New Branch
run-name: CI On New Branch


on:

  create:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    types:
      - opened

jobs:
  CI:
    uses: ./.github/workflows/ci.yml # reusable workflow file path

